Tests exception message from eval on worker context in console contains stack trace.

            function foo()
            {
                throw {a:239};
            }
            function boo()
            {
                foo();
            }
            boo();
VM:4 Uncaught Object {a: 239}VM:4 fooVM:8 booVM:10 (anonymous function) InjectedScript._evaluateOn InjectedScript._evaluateAndWrap InjectedScript.evaluate

