
This is a testharness.js-based test.
PASS Check that exception is created in called function's context. 
PASS Check that DOM exception is created in setter's context. 
PASS Check that native exception is created in setter's context. 
Harness: the test ran to completion.

